<a href="https://colab.research.google.com/github/ManojKumar-tech7/AWS-ML-PYTHON/blob/main/Day7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
# drive.mount('/content/drive')

# read data
data = open("/content/drive/MyDrive/file1.csv","r")
data.read()

'name,roll no\ndheeraj,123\nkunal,1234\nabhishek,12345\npraveen,12356\nanjali,1234567'

In [8]:
# write and read
data2 = open("/content/drive/MyDrive/hello.txt","w")
data2.write("we are indians")

data2 = open("/content/drive/MyDrive/hello.txt","r")
data2.read()


'we are indians'

In [9]:
# read and append
data2 = open("/content/drive/MyDrive/hello.txt","r")
data2.read()

data2 = open("/content/drive/MyDrive/hello.txt","a")
data2.write(" we are grrasian \n")

data2 = open("/content/drive/MyDrive/hello.txt","r")
data2.read()


'we are indians we are grrasian \n'

In [6]:
# numpy
import numpy as np
l = [10,20,30,40]
l*2

arr = np.array(l)
arr*2
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
l = [10,20,30,40]
l[0] = 100
l[-1] = 150
print(l)
# numpy
arr = np.array(l)
arr[0] = 200
arr[-1] = 250
print(arr)

[100, 20, 30, 150]
[200  20  30 250]


In [9]:
import numpy as np
l = [10,20,30,40]
# print(l+2) add not acceptable with list
arr = np.array(l)
print(arr+2)

[12 22 32 42]


In [10]:
import numpy as np
arr = np.arange(5) # start,stop,jump
print(arr)

[0 1 2 3 4]
